#!/usr/bin/env bash

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# global settings
yabai -m config external_bar               all:0:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             off          \
                window_opacity_duration    0.0          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.0          \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_border_blur         off          \
                window_animation_duration  0            \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff494d64   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                10           \
                bottom_padding             10           \
                left_padding               10           \
                right_padding              10           \
                window_gap                 10

echo "yabai configuration loaded.."

yabai -m config layout float

# Load app spaces var from vars.sh
source ~/.config/vars.sh

for index in "${app_spaces[@]}" ; do
    KEY="${index%%::*}"
    VALUE="${index##*::}"
		echo "yabai -m signal --add app='$KEY' event=application_launched action=yabai -m window --space $VALUE; yabai -m space --focus $VALUE"
    yabai -m signal --add app="$KEY" event=application_launched action="yabai -m window --space $VALUE; yabai -m space --focus $VALUE"
done

# If dock restarts, reload the scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
