#!/usr/bin/env zsh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# Reaction to events
# If dock restarts, reload the scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# $HOME/.config/yabai/store_windows.sh

# To restore a window, run this command:
#   yabai -m window --toggle float &&
#     /tmp/yabai-restore/$(yabai -m query --windows --window | jq -re '.id').restore

# global settings
yabai -m config external_bar               all:0:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             off          \
                window_opacity_duration    0.0          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.0          \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_border_blur         off          \
                window_animation_duration  0            \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff494d64   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                10           \
                bottom_padding             10           \
                left_padding               10           \
                right_padding              10           \
                window_gap                 10

echo "yabai configuration loaded.."

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Activity Monitor|General)$" manage=off
yabai -m signal --add app='Safari' event='window_title_changed' action="yabai -m rule --apply app='Safari' title='Connexion' manage=off"
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Open" title="Open" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
# Fix new tab in Finder
yabai -m signal --add app='^Finder$' event=window_created action='yabai -m space --focus next; sleep 0.01; yabai -m space --focus prev'
yabai -m signal --add app='^Finder$' event=window_destroyed action='yabai -m space --focus next; sleep 0.01; yabai -m space --focus prev'

yabai -m config layout bsp


# move some apps automatically to specific spaces
yabai -m rule --add app="Hyper" space=^3

yabai -m rule --add app="Code" space=^4

yabai -m rule --add app="Safari" space=^5

yabai -m rule --add app="Notes" space=^6

yabai -m rule --add app="Mail" space=^7
yabai -m rule --add app="Slack" space=^7

yabai -m rule --add app="Reminders" space=^8
yabai -m rule --add app="Calendar" space=^8

yabai -m rule --add app="Music" space=^9
yabai -m rule --add app="Discord" space=^9
yabai -m rule --add app="Messages" space=^9
yabai -m rule --add app="Messenger" space=^9


yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"